version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: lara_11_app_demo
        restart: unless-stopped
        working_dir: /var/www/app
        volumes:
            - .:/var/www/app
        ports:
            - "8000:8000"
            - "9003:9003"  # Xdebug port
        depends_on:
            - mysql
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root

    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root

volumes:
    mysql_data:
